### ISSUE TITLE
Multi line text support

### ISSUE THREAD

**Issue by alinturlac** [ANPez/TextImageView#1]
Hi, is there any chance of multi-line support being added? 
I've tried doing it myself following [http://stackoverflow.com/questions/3153870/canvas-drawtext-does-not-print-linebreak/15092729#15092729](url), sending in the textRect as the drawSpace to the mentioned drawMultiLine method, but the 
`if(calculateWidthFromFontSize(line + " " + lines[i], fontSize) <= drawSpace.width())` 
line gets evaluated to true every single time, regardless of the text size. (newbie here)

**Comment by anpez** [comment]
Added. Thanks for using the library.

**Comment by alinturlac** [comment]
Thank you so much for the quick implementation!
