### ISSUE TITLE
What if I'd like to add another textview to the image?

### ISSUE THREAD

**Issue by Odaym** [ANPez/TextImageView#2]
using `setText()` on the image just changes the currently added text of course. Any ideas? Thanks

**Comment by anpez** [comment]
This gets scheduled for the next version which should be out whenever this week. Thanks for your ideas.

**Comment by anpez** [comment]
Just uploaded v3.0 that covers this. Hope everything is ok, if it is not, just file a new issue. Thanks!

**Comment by Odaym** [comment]
That's great and really good job on implementing that so quickly, I'll add another issue as Enhancement over this, hope you'll see it just as beneficial

**Comment by Odaym** [comment]
Actually, this is a strange implementation that I first thought was bugged because when you add a new text you can no longer the text that was added before that so you can only control one textview at a time.

I guess this is better but I had to deduce that there must be a `removeText()` method, which there is, thanks!

**Comment by anpez** [comment]
It could definitely be buggy :laughing: 
I did this implementation because it fits my needs. If you need it to work differently, I'm always glad to hear suggestions!
