### ISSUE TITLE
Toggle scale and rotation from UI

### ISSUE THREAD

**Issue by Odaym** [ANPez/TextImageView#3]
I thought that now since there is such a thing as rotationEnabled and scaleEnabled, you can have setters/getters for those properties so that maybe when working with a photo editor let's say, the user adds a textfield and on that textfield there is a scale button and a rotate button, onClick of those two controls, scaling and rotation would be enabled and then disabled. Not just free controls all the time, just a suggestion, let me know if it makes sense

**Comment by anpez** [comment]
It should be fixed in new version 3.1. Thanks for your comments!
